#!/bin/bash
export OPENSSL_LIB_DIR=/usr/lib/x86_64-linux-gnu/libssl # while pkg-config is not installed
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd $SCRIPT_DIR
cargo build --release --locked --offline
